-- Views on parametricity
--
-- From point of view of implementor:
--
--   A polymorphic type *constrains* an implementation.
--   (This is a good thing).
--
-- From point of view of user:
--
--   A polymorphic type reveals *guarantees* about an
--   implementation of that type.
