-- Bonus theory (thanks Dave!)
--
--
-- * Church encoding: encoding of algebraic data types
--   using functions only.
--
-- * "Tagless final" interpreters, Oleg Kiselyov
--    http://okmij.org/ftp/tagless-final/course/lecture.pdf
--
-- * Haste and Tagless Final Style:
--    http://www.slideshare.net/takeoutweight/haste-and-tagless-final-style
