-- Haskell type classes vs Java interfaces
--
-- * similar to interfaces (in intent, at least)
--
-- * Java implementations are declared within the class
--
-- * Haskell instances are declared separately from the type
--
-- * type classes are more general
--   * multi-parameter type classes
--   * inference-friendly
--   * no implicit "invocant" argument
