-- Homework tips
--
--
-- * Do ALL the exercises.
--
-- * The 'FlexibleInstances' language extension is needed sooner
--   than stated.
--
-- * Typo in exercise 5; should be 'stackVM exp == Right (IVal exp)'
--
-- * 'import qualified ...' may needed to avoid name collisions.
--
-- * 'Control.Applicative' module is useful in at least one of the
--   later problems.
