-- Homework tips
--
--
-- * Do ALL the exercises.
--
-- * The 'FlexibleInstances' language extension is needed sooner
--   than stated.
--
-- * Typo in exercise 5; should be 'stackVM exp == Right (IVal exp)'
--
-- * 'import qualified ...' may be needed to avoid name collisions.
